In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

2024-04-04 19:47:49.088746: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-04 19:47:49.090298: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-04 19:47:49.117481: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-04 19:47:49.118145: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-04 19:47:49.525666: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [2]:
# read the training data set
data = pd.read_excel('hand_features_data.xlsx')

# top rows of the data
data.head()

# seperate the independent and target variables
X = data.iloc[:, 1:]
y = data.iloc[:, 0]

encoder = OneHotEncoder(sparse=False)
y_encoded = encoder.fit_transform(y.values.reshape(-1, 1))

/home/swapnil/.local/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [3]:
X

f1        f2        f3        f4        f5        f6        f7  \
0    2.012502  0.221707  2.438079  0.505950  2.622909  0.757923  3.588601   
1    2.076664  0.194695  2.700717  0.395163  2.917479  0.586849  3.582830   
2    1.959751  0.178725  2.477504  0.366654  2.671019  0.529144  3.136095   
3    1.981047  0.226440  2.600246  0.487529  3.027171  0.655250  3.338329   
4    2.042190  0.251271  2.687520  0.519462  3.181523  0.692673  3.524078   
..        ...       ...       ...       ...       ...       ...       ...   
395  2.161567  0.254349  2.955648  0.443055  3.416948  0.556647  3.185656   
396  2.417826  0.161811  3.433636  0.307956  4.180878  0.391272  4.153226   
397  2.037362  0.174746  2.511528  0.415723  2.625616  0.616940  3.074696   
398  2.059372  0.214582  2.579550  0.469940  2.662650  0.661305  3.252017   
399  1.970517  0.153651  2.449549  0.376519  2.517792  0.581885  2.904929   

           f8        f9       f10  ...       f29       f30       f31  \
0    0.575544  5.053895  0.574802  ...  2.638038  0.826151  2.589627   
1    0.615518  5.030980  0.610827  ...  2.198519  0.589494  2.634794   
2    0.499009  4.410028  0.493660  ...  2.319633  0.517630  2.207489   
3    0.399861  4.717362  0.396842  ...  2.526374  0.662258  2.459309   
4    0.433778  4.941984  0.447634  ...  2.750091  0.706314  2.669912   
..        ...       ...       ...  ...       ...       ...       ...   
395  0.430449  4.506188  0.481145  ...  2.444739  0.711023  2.611147   
396  0.166086  5.921208  0.206908  ...  3.327913  0.488006  3.481176   
397  0.413482  4.315129  0.441150  ...  2.216096  0.673241  2.406743   
398  0.504962  4.553872  0.530775  ...  2.445662  0.756775  2.577089   
399  0.436283  4.119077  0.455108  ...  1.936371  0.633043  2.284801   

          f32       f33       f34       f35       f36       f37       f38  
0    1.173639  3.200658  1.076328  2.741661  1.017778  2.279434  0.980404  
1    1.139123  3.099999  0.945403  2.543667  0.809314  2.043178  0.709426  
2    1.001590  2.730308  0.865236  2.481866  0.742442  2.155402  0.657768  
3    0.931929  3.036416  0.867964  2.635757  0.837925  2.246042  0.839819  
4    0.964991  3.448801  0.907046  3.018056  0.880908  2.598565  0.874303  
..        ...       ...       ...       ...       ...       ...       ...  
395  0.932159  3.163002  0.881492  2.745852  0.865313  2.353401  0.871995  
396  0.634059  4.209879  0.619682  3.715920  0.631159  3.273808  0.646621  
397  0.948844  3.074674  0.895727  2.664676  0.851000  2.259070  0.849139  
398  1.030077  3.221709  0.968334  2.841266  0.919292  2.405149  0.916319  
399  0.967576  2.813351  0.883364  2.440838  0.821834  2.043784  0.807902  

[400 rows x 38 columns]

In [4]:
y_encoded

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [5]:
pipeline = Pipeline([
    ('preprocessing', StandardScaler()),
    ('model', MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42))
])

In [6]:
pipeline

Pipeline(steps=[('preprocessing', StandardScaler()),
                ('model',
                 MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000,
                               random_state=42))])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [8]:
X_train

f1        f2        f3        f4        f5        f6        f7  \
3    1.981047  0.226440  2.600246  0.487529  3.027171  0.655250  3.338329   
18   1.980282  0.190757  2.552136  0.448004  2.976979  0.626777  3.336714   
202  2.258195  0.110442  3.333789  0.153176  4.101253  0.239631  3.135008   
250  2.060245 -0.089847  2.914222 -0.280769  3.500561 -0.421476  3.110428   
274  1.863256  0.122767  2.498671  0.137815  2.999532  0.208602  2.536791   
..        ...       ...       ...       ...       ...       ...       ...   
71   1.963492  0.230614  2.193964  0.584262  2.223537  0.918228  3.720520   
106  2.205534  0.212420  3.083237  0.226912  3.706692  0.178636  3.234621   
270  2.034480  0.134898  2.802252  0.159618  3.332019  0.223839  2.637724   
348  2.082663  0.183622  2.707885  0.294231  3.094066  0.336056  3.498492   
102  2.288603  0.276457  3.372100  0.339266  4.181429  0.302883  3.393572   

           f8        f9       f10  ...       f29       f30       f31  \
3    0.399861  4.717362  0.396842  ...  2.526374  0.662258  2.459309   
18   0.382817  4.674411  0.367223  ...  2.600470  0.637595  2.512289   
202  0.728342  4.404382  0.651289  ...  4.592178  0.479192  3.259128   
250  0.216461  4.188876 -0.114094  ...  4.015106 -0.531220  2.917031   
274  0.715022  3.411440  0.634085  ...  3.063640  0.367633  2.322591   
..        ...       ...       ...  ...       ...       ...       ...   
71   0.588667  5.259868  0.610200  ...  2.481968  0.939194  2.617972   
106  0.846258  4.647375  0.960303  ...  1.640913  1.055066  2.795589   
270  0.674473  3.621190  0.606618  ...  3.325915  0.328519  2.372813   
348  0.635915  5.025318  0.661840  ...  2.273898  0.547746  2.668973   
102  0.910574  4.999908  1.036373  ...  1.825982  1.268141  2.916091   

          f32       f33       f34       f35       f36       f37       f38  
3    0.931929  3.036416  0.867964  2.635757  0.837925  2.246042  0.839819  
18   0.908791  3.203906  0.876646  2.935046  0.856236  2.564439  0.847164  
202  0.863947  4.406711  0.772724  4.709074  0.651549  4.644441  0.547724  
250 -0.220481  4.053991 -0.349768  4.235718 -0.470354  4.142197 -0.575816  
274  0.821027  3.203450  0.662251  3.299719  0.508629  3.092582  0.384939  
..        ...       ...       ...       ...       ...       ...       ...  
71   1.222433  2.926729  1.205619  2.578422  1.142173  2.247784  1.065854  
106  1.436533  3.293329  1.339199  2.602399  1.300583  2.116554  1.295126  
270  0.830130  3.276153  0.650877  3.398877  0.478530  3.229788  0.341271  
348  1.077539  3.170820  0.870686  2.685613  0.733142  2.224195  0.680769  
102  1.514730  3.418064  1.520870  2.542858  1.538003  2.025147  1.515231  

[320 rows x 38 columns]

In [9]:
print("X_train.shape = ", X_train.shape)
print("X_test.shape = ", X_test.shape)
print("y_train.shape = ", y_train.shape)
print("y_test.shape = ", y_test.shape)

X_train.shape =  (320, 38)
X_test.shape =  (80, 38)
y_train.shape =  (320, 4)
y_test.shape =  (80, 4)


In [12]:
# pipeline.named_steps['model'].compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
pipeline.fit(X_train, y_train)

# pipeline.fit(X_train, y_train))


Pipeline(steps=[('preprocessing', StandardScaler()),
                ('model',
                 MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000,
                               random_state=42))])

In [13]:
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.975


In [14]:
X_test

f1        f2        f3        f4        f5        f6        f7  \
209  1.847600  0.083193  2.583246  0.106759  3.209357  0.186910  2.567246   
280  1.950270  0.108919  2.692431  0.107159  3.295694  0.127215  2.627181   
33   1.954374  0.182970  2.453901  0.412537  2.664701  0.610366  3.277917   
210  1.798824  0.102272  2.430282  0.115344  2.969394  0.181245  2.678129   
93   1.966653  0.226387  2.607252  0.448858  3.081276  0.554734  3.062288   
..        ...       ...       ...       ...       ...       ...       ...   
246  1.862566  0.061685  2.488923  0.061695  2.909706  0.141017  2.368437   
227  1.913729  0.114355  2.647171  0.099249  3.263440  0.113351  2.771297   
369  2.132688  0.264967  2.670192  0.548165  2.952889  0.747995  3.389234   
176  2.333770  0.221057  3.303869  0.237875  4.011177  0.206768  3.315697   
289  2.041956  0.099248  2.903459  0.131090  3.477383  0.240712  2.720722   

           f8        f9       f10  ...       f29       f30       f31  \
209  0.693712  3.458652  0.573685  ...  3.378430  0.367142  2.655380   
280  0.747545  3.590205  0.550202  ...  3.590748  0.251681  2.339853   
33   0.569226  4.618153  0.574773  ...  2.190958  0.662255  2.334265   
210  0.789746  3.457939  0.585569  ...  3.190480  0.279548  2.379424   
93   0.389782  4.386879  0.378866  ...  2.296641  0.553082  2.325881   
..        ...       ...       ...  ...       ...       ...       ...   
246  0.555053  3.192141  0.498989  ...  2.946165  0.231623  2.182050   
227  0.781695  3.560705  0.536432  ...  3.804768  0.262186  2.764754   
369  0.562588  4.777285  0.592961  ...  2.167548  0.748919  2.472999   
176  0.776018  4.719795  0.877890  ...  2.056955  0.977995  2.666910   
289  0.654671  3.713421  0.627011  ...  3.477480  0.413947  2.673722   

          f32       f33       f34       f35       f36       f37       f38  
209  0.840458  3.595159  0.695751  3.692031  0.544641  3.462018  0.417705  
280  0.772075  3.313077  0.568669  3.562154  0.419301  3.473159  0.302920  
33   1.122151  2.834243  0.987395  2.489584  0.876940  2.108695  0.811733  
210  0.738941  3.184874  0.559543  3.286011  0.417826  3.159874  0.305091  
93   0.926845  2.847837  0.873869  2.506073  0.779640  2.184210  0.702695  
..        ...       ...       ...       ...       ...       ...       ...  
246  0.738259  2.915334  0.584472  2.998719  0.407035  2.854446  0.264536  
227  0.700982  3.712678  0.550588  3.861945  0.412043  3.769470  0.292133  
369  1.157080  3.000566  1.046132  2.397874  0.974853  1.969830  0.967749  
176  1.305673  3.002715  1.268401  2.350581  1.239222  2.077483  1.202052  
289  0.842132  3.633668  0.712819  3.758397  0.560446  3.530388  0.445562  

[80 rows x 38 columns]

In [15]:
instance = 31
test_instance = X_test.iloc[instance].values
print(pipeline.predict(test_instance.reshape(1, -1)))
test_instance_prediction = np.argmax(pipeline.predict(test_instance.reshape(1, -1)), axis=1)
print(np.argmax(y_test[instance]), ' ? ', test_instance_prediction[0])

[[1 0 0 0]]
0  ?  0


/home/swapnil/.local/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/home/swapnil/.local/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [16]:
test_instance

array([2.37189476, 0.20876813, 3.27931701, 0.22809622, 3.99007421,
       0.20324435, 3.49472386, 0.72169275, 4.93924163, 0.76643525,
       5.82767092, 0.79314641, 6.66723016, 0.81611102, 3.44074815,
       0.90026525, 3.5047695 , 0.80306443, 2.71771593, 0.74353703,
       2.47169171, 0.77060461, 3.20650712, 1.08996897, 3.09429452,
       0.98058483, 2.38436277, 0.9434237 , 2.28095253, 0.9771524 ,
       2.97626788, 1.32041967, 2.99594091, 1.2027779 , 2.465122  ,
       1.15910754, 2.30601824, 1.16389145])

In [17]:
test_instance.reshape(1, -1)

array([[2.37189476, 0.20876813, 3.27931701, 0.22809622, 3.99007421,
        0.20324435, 3.49472386, 0.72169275, 4.93924163, 0.76643525,
        5.82767092, 0.79314641, 6.66723016, 0.81611102, 3.44074815,
        0.90026525, 3.5047695 , 0.80306443, 2.71771593, 0.74353703,
        2.47169171, 0.77060461, 3.20650712, 1.08996897, 3.09429452,
        0.98058483, 2.38436277, 0.9434237 , 2.28095253, 0.9771524 ,
        2.97626788, 1.32041967, 2.99594091, 1.2027779 , 2.465122  ,
        1.15910754, 2.30601824, 1.16389145]])

In [18]:
import joblib
joblib.dump(pipeline, 'my_pipeline.joblib')

['my_pipeline.joblib']

In [19]:
loaded_pipeline = joblib.load('my_pipeline.joblib')


In [20]:
loaded_pipeline

Pipeline(steps=[('preprocessing', StandardScaler()),
                ('model',
                 MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000,
                               random_state=42))])

In [21]:
instance = 30
test_instance = X_test.iloc[instance].values
test_instance_prediction = np.argmax(loaded_pipeline.predict(test_instance.reshape(1, -1)), axis=1)
print(np.argmax(y_test[instance]), ' ? ', test_instance_prediction[0])

3  ?  3


/home/swapnil/.local/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
